"use client";

import { useVision } from '@/lib/store/vision-context';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { useState } from 'react';

export function DownloadResultsButton() {
    const { leftEyeResult, rightEyeResult, contrastResult } = useVision();
    const [isGenerating, setIsGenerating] = useState(false);

    const generatePDF = async () => {
        setIsGenerating(true);
        const doc = new jsPDF();

        // --- HEADER ---
        doc.setFillColor(30, 41, 59); // Slate 900
        doc.rect(0, 0, 210, 40, 'F');

        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.setFont('helvetica', 'bold');
        doc.text("IRIS Vision Report", 20, 25);

        doc.setFontSize(10);
        doc.setFont('helvetica', 'normal');
        doc.text("Professional Online Screening", 20, 32);

        const date = new Date().toLocaleDateString();
        doc.text(`Date: ${date}`, 160, 25);

        let y = 60;
        doc.setTextColor(30, 41, 59);

        // --- SECTION: VISUAL ACUITY ---
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text("Visual Acuity (Snellen)", 20, y);
        y += 10;

        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');

        // Use actual context data if available, otherwise N/A
        const acuityLeft = leftEyeResult?.acuity || "N/A";
        const acuityRight = rightEyeResult?.acuity || "N/A";

        doc.text(`Right Eye (OD): ${acuityRight}`, 20, y);
        y += 8;
        doc.text(`Left Eye (OS): ${acuityLeft}`, 20, y);
        y += 15;

        // --- SECTION: CONTRAST SENSITIVITY ---
        if (contrastResult) {
            doc.setFontSize(16);
            doc.setFont('helvetica', 'bold');
            doc.text("Contrast Sensitivity", 20, y);
            y += 10;

            doc.setFontSize(12);
            doc.setFont('helvetica', 'normal');
            doc.text(`Score: ${contrastResult.score || 'N/A'}`, 20, y);
            y += 8;
            doc.text(`Sensitivity Level: ${contrastResult.label || 'N/A'}`, 20, y);
            y += 8;
            doc.text(`Interpretation: ${contrastResult.sensitivity || 'Standard'}`, 20, y);
            y += 15;
        }

        // --- SECTION: COLOR VISION ---
        // Placeholder for when we add Color test
        doc.setFontSize(16);
        doc.setFont('helvetica', 'bold');
        doc.text("Color Vision (Ishihara)", 20, y);
        y += 10;
        doc.setFontSize(12);
        doc.setFont('helvetica', 'normal');
        doc.text("Result: Normal Color Vision (Sample)", 20, y);
        y += 15;

        // --- FOOTER ---
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text("Disclaimer: This report is generated by an online screening tool and is not a medical diagnosis.", 20, 280);
        doc.text("Please consult a certified optometrist for a comprehensive eye exam.", 20, 285);

        doc.save("Iris_Vision_Report.pdf");
        setIsGenerating(false);
    };

    return (
        <Button
            onClick={generatePDF}
            disabled={isGenerating}
            className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white"
        >
            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <FileDown className="w-4 h-4" />}
            Download Full Report
        </Button>
    );
}
